spring:
  datasource:
    url:  jdbc:h2:E:\Study\Project\saesumMBTI\saesumMBTI
    username: kyu
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080

